<a href="https://colab.research.google.com/github/warp007x/day-2-ML/blob/main/day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# defining an array with data

In [1]:
import numpy as np
arr1 = np.empty((2,3))

arr2 = np.array([[10,2,3], [23,45,67]])
print(arr2)



[[10  2  3]
 [23 45 67]]


In [2]:
var3= np.empty((2,3),dtype=np.int)
var3[0][0]=5.8
var3[0][1]=2
var3[1][0]=56.4
var3[1][1]=200

print(var3) 


[[  5   2   0]
 [ 56 200   0]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [3]:
var3= np.empty((2,3),dtype=int)
var3[0][0]=5.8
var3[0][1]=2
var3[1][0]=56.4
var3[1][1]=200

print(var3) 


[[  5   2   0]
 [ 56 200   0]]


## defing 2-d array

In [4]:
var2=np.array([[10,2,3], [23,45,67],[1,2,3]])
print(var2)

[[10  2  3]
 [23 45 67]
 [ 1  2  3]]


# concatinate 2 arrays

### axis=0 => add vertically(rowwise addition)

In [5]:
arr_concat= np.concatenate((var2, var3), axis=0)
print(arr_concat)

[[ 10   2   3]
 [ 23  45  67]
 [  1   2   3]
 [  5   2   0]
 [ 56 200   0]]


### axis=1 => add horizontally(coloumnwise addition)

In [6]:
ar1= np.array([[1,2,2],[1,3,4],[2,4,6],[2,3,4]])
ar2= np.array([[1,2,2],[1,3,4],[2,4,6]])
ar3= np.array([[1,2],[1,4],[2,6]])
ar4= np.array([[1,2,2],[1,3,4],[2,4,6]])
print(ar1.shape)
print(ar2.shape)
print(ar3.shape)
print(ar4.shape)
arr_concat1= np.concatenate((ar1, ar2), axis=0)
arr_concat2= np.concatenate((ar3, ar4), axis=1)
print(arr_concat2)




(4, 3)
(3, 3)
(3, 2)
(3, 3)
[[1 2 1 2 2]
 [1 4 1 3 4]
 [2 6 2 4 6]]


## Reshaping an Array

In [7]:
print(ar1)
ar5=np.reshape(ar1,(3,4))
print("\n",ar5)


[[1 2 2]
 [1 3 4]
 [2 4 6]
 [2 3 4]]

 [[1 2 2 1]
 [3 4 2 4]
 [6 2 3 4]]


- transpose of a matrix
- generating zero mareix
- generating one matrix 

In [8]:
print(np.transpose(ar2))
print("\n",np.zeros((3,3),dtype=int))
print("\n",np.ones((3,3),dtype=int))

[[1 1 2]
 [2 3 4]
 [2 4 6]]

 [[0 0 0]
 [0 0 0]
 [0 0 0]]

 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [9]:
print("\n",ar2[[1,2],0])
print("\n",ar2[:,0])


 [1 2]

 [1 1 2]
